//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int user_id { get; set; }
        public string Emp_Name { get; set; }
        public string Gender { get; set; }
        public string DateofBirth { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
