//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD
    {
        public int sno { get; set; }
        public string Accoun_no { get; set; }
        public string mode { get; set; }
        public Nullable<decimal> rupees { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<decimal> intrest_rate { get; set; }
        public string Maturity_date { get; set; }
        public Nullable<decimal> Maturity_amount { get; set; }
        public string start_date { get; set; }
    }
}
